---
- name: regex example 
  command: /tmp/test.sh
  register: regexoutput

- name: output
  debug:
    var: regexoutput.stdout

- name: set fact
  set_fact:
    myvalue: "{{ regexoutput.stdout | regex_search(regexp) }}"
  vars:
    regexp: 'kubeadm join .*'

- name: debug myvalue
  debug:
    var: myvalue
