---
- name: restart nfs-server
  service:
    name: "nfs-server"
    state: "restarted"
    enabled: true


- name: restart firewalld
  service:
    name: "firewalld"
    state: "restarted"
    enabled: true

